title: Centro educativo Nuestra señora de la Salceda
description: Página creada con Jekyll y GitHub Pages
# remote_theme: mmistakes/minimal-mistakes@4.33.0
remote_theme: mmistakes/minimal-mistakes@4.27.3
minimal_mistakes_skin: "aqua" # "default" , "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
site.locale: "es-ES"

paginate: 5 # amount of posts to show
paginate_path: /page:num/
paginate_path: /_posts/page:num

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

header_pages:
  - index.md
  - ciclos.md
  - noticias.md
  - about.md
  - contact.md
